// Generated by CIRCT firtool-1.137.0-1-gfcc42190a
module AddRawFN(	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:47:7
  input         io_a_isNaN,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
                io_a_isInf,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
                io_a_isZero,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
                io_a_sign,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
  input  [9:0]  io_a_sExp,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
  input  [24:0] io_a_sig,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
  input         io_b_isNaN,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
                io_b_isInf,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
                io_b_isZero,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
                io_b_sign,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
  input  [9:0]  io_b_sExp,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
  input  [24:0] io_b_sig,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
  output        io_invalidExc,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
                io_rawOut_isNaN,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
                io_rawOut_isInf,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
                io_rawOut_isZero,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
                io_rawOut_sign,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
  output [9:0]  io_rawOut_sExp,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
  output [26:0] io_rawOut_sig	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16
);

  wire [9:0]  _sDiffExps_T = io_a_sExp - io_b_sExp;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:63:31
  wire        _common_sExpOut_T = $signed(_sDiffExps_T) < 10'sh0;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:63:31, :64:41, :95:{45,49,98}
  wire [4:0]  _modNatAlignDist_T_4 =
    _common_sExpOut_T ? io_b_sExp[4:0] - io_a_sExp[4:0] : _sDiffExps_T[4:0];	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16, :63:31, :64:{30,41,58}
  wire        isMaxAlign =
    (|(_sDiffExps_T[9:5])) & (_sDiffExps_T[9:5] != 5'h1F | _sDiffExps_T[4:0] == 5'h0);	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:63:31, :66:{19,37,45}, :67:{42,51,63,87}, :68:24
  wire [4:0]  alignDist = isMaxAlign ? 5'h1F : _modNatAlignDist_T_4;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:64:30, :66:45, :68:24
  wire        far_subMags = io_a_sign != io_b_sign;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:61:29, :69:24
  wire        closeSubMags = far_subMags & ~isMaxAlign & _modNatAlignDist_T_4 < 5'h2;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:61:29, :64:30, :66:45, :69:{24,33,36,48,68}
  wire        _close_alignedSigA_T_5 = $signed(_sDiffExps_T) > -10'sh1;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:63:31, :73:18
  wire [26:0] _close_alignedSigA_T_4 =
    _close_alignedSigA_T_5 & _sDiffExps_T[0] ? {io_a_sig, 2'h0} : 27'h0;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:63:31, :73:{12,18,32,45,58}
  wire [25:0] _GEN =
    _close_alignedSigA_T_4[25:0]
    | (_close_alignedSigA_T_5 & ~(_sDiffExps_T[0]) ? {io_a_sig, 1'h0} : 26'h0);	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:63:31, :73:{12,18,45,68}, :74:{12,32,35,58}
  wire [26:0] _close_sSigSum_T_3 =
    {_close_alignedSigA_T_4[26],
     _GEN[25],
     _GEN[24:0] | (_common_sExpOut_T ? io_a_sig : 25'h0)}
    - {io_b_sig[24], io_b_sig, 1'h0};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:64:41, :73:{12,68}, :74:68, :75:12, :76:50
  wire        _close_notTotalCancellation_signOut_T =
    $signed(_close_sSigSum_T_3) < 27'sh0;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:76:50, :77:42
  wire [25:0] _close_sigSum_T_4 =
    _close_notTotalCancellation_signOut_T
      ? 26'h0 - _close_sSigSum_T_3[25:0]
      : _close_sSigSum_T_3[25:0];	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:64:41, :76:50, :77:{27,42,49}
  wire [3:0]  close_normDistReduced2 =
    (|(_close_sigSum_T_4[25:24]))
      ? 4'h0
      : (|(_close_sigSum_T_4[23:22]))
          ? 4'h1
          : (|(_close_sigSum_T_4[21:20]))
              ? 4'h2
              : (|(_close_sigSum_T_4[19:18]))
                  ? 4'h3
                  : (|(_close_sigSum_T_4[17:16]))
                      ? 4'h4
                      : (|(_close_sigSum_T_4[15:14]))
                          ? 4'h5
                          : (|(_close_sigSum_T_4[13:12]))
                              ? 4'h6
                              : (|(_close_sigSum_T_4[11:10]))
                                  ? 4'h7
                                  : (|(_close_sigSum_T_4[9:8]))
                                      ? 4'h8
                                      : (|(_close_sigSum_T_4[7:6]))
                                          ? 4'h9
                                          : (|(_close_sigSum_T_4[5:4]))
                                              ? 4'hA
                                              : (|(_close_sigSum_T_4[3:2])) ? 4'hB : 4'hC;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:77:{27,79}, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:103:{33,54}, :106:{15,57}, src/main/scala/chisel3/util/Mux.scala:58:84
  wire [56:0] _close_sigOut_T =
    {31'h0, _close_sigSum_T_4} << {52'h0, close_normDistReduced2, 1'h0};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:77:27, :82:38, src/main/scala/chisel3/util/Mux.scala:58:84
  wire [23:0] _far_sigSmaller_T_1 = _common_sExpOut_T ? io_a_sig[23:0] : io_b_sig[23:0];	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16, :64:41, :89:29
  wire [28:0] far_mainAlignedSigSmaller = {_far_sigSmaller_T_1, 5'h0} >> alignDist;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:68:24, :89:29, :90:{52,56}
  wire [8:0]  far_roundExtraMask_shift = $unsigned($signed(9'sh100 >>> alignDist[4:2]));	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:68:24, :92:47, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:76:56
  wire [9:0]  _GEN_0 =
    {far_mainAlignedSigSmaller[2:0],
     {|(_far_sigSmaller_T_1[23:22]),
      |(_far_sigSmaller_T_1[21:18]),
      |(_far_sigSmaller_T_1[17:14]),
      |(_far_sigSmaller_T_1[13:10]),
      |(_far_sigSmaller_T_1[9:6]),
      |(_far_sigSmaller_T_1[5:2]),
      |(_far_sigSmaller_T_1[1:0])}
       & {far_roundExtraMask_shift[1],
          far_roundExtraMask_shift[2],
          far_roundExtraMask_shift[3],
          far_roundExtraMask_shift[4],
          far_roundExtraMask_shift[5],
          far_roundExtraMask_shift[6],
          far_roundExtraMask_shift[7]}};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:89:29, :90:56, :95:{38,45,49,76,98}, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:76:56, :77:20, :78:22, :120:{33,54}, :123:{15,57}, :124:20
  wire        _GEN_1 = io_a_sign == io_b_sign;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:61:29, :69:24, :97:39
  wire [27:0] _far_sigSum_T_3 =
    {1'h0, _common_sExpOut_T ? io_b_sig[23:0] : io_a_sig[23:0], 3'h0}
    + (_GEN_1
         ? {1'h0, far_mainAlignedSigSmaller[28:3], |_GEN_0}
         : {1'h1, ~{far_mainAlignedSigSmaller[28:3], |_GEN_0}}) + {27'h0, far_subMags};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:49:16, :61:29, :64:41, :69:{24,68}, :88:29, :90:56, :94:{12,38}, :95:{45,49,98}, :97:{39,56,62}, :98:{36,41,68}
  wire        notNaN_isInfOut = io_a_isInf | io_b_isInf;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:103:38
  wire        addZeros = io_a_isZero & io_b_isZero;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:104:32
  wire        notNaN_specialCase = notNaN_isInfOut | addZeros;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:103:38, :104:32, :105:46
  assign io_invalidExc =
    io_a_isNaN & ~(io_a_sig[22]) | io_b_isNaN & ~(io_b_sig[22]) | io_a_isInf & io_b_isInf
    & far_subMags;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:47:7, :61:29, :69:24, :102:{43,57}, :121:{45,71}, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/common.scala:82:{46,49,56}
  assign io_rawOut_isNaN = io_a_isNaN | io_b_isNaN;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:47:7, :125:35
  assign io_rawOut_isInf = notNaN_isInfOut;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:47:7, :103:38
  assign io_rawOut_isZero =
    addZeros | ~notNaN_isInfOut & closeSubMags & ~(|(_close_sigOut_T[25:24]));	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:47:7, :69:{33,48}, :82:{38,63}, :83:{35,49,82}, :103:38, :104:32, :106:{37,41,58,74}
  assign io_rawOut_sign =
    io_a_sign == io_b_sign & io_a_sign | io_a_isInf & io_a_sign | io_b_isInf & io_b_sign
    | ~notNaN_specialCase & closeSubMags & (|(_close_sigOut_T[25:24]))
    & (io_a_sign ^ _close_notTotalCancellation_signOut_T) | ~notNaN_specialCase
    & ~closeSubMags & (_common_sExpOut_T ? io_b_sign : io_a_sign);	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:47:7, :61:29, :64:41, :69:{33,48}, :77:42, :82:{38,63}, :83:{49,82}, :84:56, :87:26, :105:46, :108:{39,63}, :109:{39,63}, :110:39, :111:63, :112:{10,30,46}, :113:{38,77}, :114:{30,33,47}
  assign io_rawOut_sExp =
    (closeSubMags | _common_sExpOut_T ? io_b_sExp : io_a_sExp)
    - {5'h0, closeSubMags ? {close_normDistReduced2, 1'h0} : {4'h0, far_subMags}};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:47:7, :61:29, :64:41, :69:{24,33,48}, :81:53, :116:{13,27}, :117:{13,18}, src/main/scala/chisel3/util/Mux.scala:58:84
  assign io_rawOut_sig =
    closeSubMags
      ? {_close_sigOut_T[25:0], 1'h0}
      : _GEN_1
          ? {_far_sigSum_T_3[27:2], _far_sigSum_T_3[1] | _far_sigSum_T_3[0]}
          : _far_sigSum_T_3[26:0];	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/AddRecFN.scala:47:7, :61:29, :69:{24,33,48}, :82:{38,63}, :97:39, :98:{41,68}, :99:{25,62,67,79}, :118:28
endmodule

