// Generated by CIRCT firtool-1.137.0-1-gfcc42190a

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Borg(	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
  input         clock,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
                reset,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
  input  [5:0]  io_address,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:7:16
  input  [31:0] io_data_in,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:7:16
  input  [1:0]  io_data_write_n,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:7:16
                io_data_read_n,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:7:16
  output [31:0] io_data_out,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:7:16
  output        io_data_ready,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:7:16
  input  [7:0]  io_ui_in,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:7:16
  output [7:0]  io_uo_out,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:7:16
  output        io_user_interrupt	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:7:16
);

  wire [32:0] _f_mul_io_out;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:47:23
  wire [32:0] _f_add_io_out;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:40:23
  reg  [31:0] operand_A_bits;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:20:33
  reg  [31:0] operand_B_bits;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:21:33
  wire        recA_rawIn_isZeroExpIn = operand_A_bits[30:23] == 8'h0;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:20:33, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:45:19, :48:30
  wire [4:0]  recA_rawIn_normDist =
    operand_A_bits[22]
      ? 5'h0
      : operand_A_bits[21]
          ? 5'h1
          : operand_A_bits[20]
              ? 5'h2
              : operand_A_bits[19]
                  ? 5'h3
                  : operand_A_bits[18]
                      ? 5'h4
                      : operand_A_bits[17]
                          ? 5'h5
                          : operand_A_bits[16]
                              ? 5'h6
                              : operand_A_bits[15]
                                  ? 5'h7
                                  : operand_A_bits[14]
                                      ? 5'h8
                                      : operand_A_bits[13]
                                          ? 5'h9
                                          : operand_A_bits[12]
                                              ? 5'hA
                                              : operand_A_bits[11]
                                                  ? 5'hB
                                                  : operand_A_bits[10]
                                                      ? 5'hC
                                                      : operand_A_bits[9]
                                                          ? 5'hD
                                                          : operand_A_bits[8]
                                                              ? 5'hE
                                                              : operand_A_bits[7]
                                                                  ? 5'hF
                                                                  : operand_A_bits[6]
                                                                      ? 5'h10
                                                                      : operand_A_bits[5]
                                                                          ? 5'h11
                                                                          : operand_A_bits[4]
                                                                              ? 5'h12
                                                                              : operand_A_bits[3]
                                                                                  ? 5'h13
                                                                                  : operand_A_bits[2]
                                                                                      ? 5'h14
                                                                                      : operand_A_bits[1]
                                                                                          ? 5'h15
                                                                                          : 5'h16;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:20:33, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:91:52, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:46:21, src/main/scala/chisel3/util/Mux.scala:58:84
  wire [53:0] _recA_rawIn_subnormFract_T =
    {31'h0, operand_A_bits[22:0]} << recA_rawIn_normDist;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:20:33, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:46:21, :52:33, src/main/scala/chisel3/util/Mux.scala:58:84
  wire [8:0]  _recA_rawIn_adjustedExp_T_4 =
    (recA_rawIn_isZeroExpIn
       ? {4'hF, ~recA_rawIn_normDist}
       : {1'h0, operand_A_bits[30:23]}) + {7'h20, recA_rawIn_isZeroExpIn ? 2'h2 : 2'h1};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7, :20:33, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:45:19, :48:30, :54:10, :55:18, :57:9, :58:14, src/main/scala/chisel3/util/Mux.scala:58:84
  wire [2:0]  _recA_T_1 =
    recA_rawIn_isZeroExpIn & ~(|(operand_A_bits[22:0]))
      ? 3'h0
      : _recA_rawIn_adjustedExp_T_4[8:6];	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7, :20:33, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:46:21, :48:30, :49:34, :57:9, :60:30, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/recFNFromFN.scala:48:{15,50}
  wire [32:0] recA =
    {operand_A_bits[31],
     _recA_T_1[2:1],
     _recA_T_1[0] | (&(_recA_rawIn_adjustedExp_T_4[8:7])) & (|(operand_A_bits[22:0])),
     _recA_rawIn_adjustedExp_T_4[5:0],
     recA_rawIn_isZeroExpIn
       ? {_recA_rawIn_subnormFract_T[21:0], 1'h0}
       : operand_A_bits[22:0]};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:20:33, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:44:18, :46:21, :48:30, :49:34, :52:{33,46,64}, :57:9, :61:{32,57}, :64:28, :70:33, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/recFNFromFN.scala:48:{15,76}, :50:{23,41}
  wire        recB_rawIn_isZeroExpIn = operand_B_bits[30:23] == 8'h0;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:21:33, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:45:19, :48:30
  wire [4:0]  recB_rawIn_normDist =
    operand_B_bits[22]
      ? 5'h0
      : operand_B_bits[21]
          ? 5'h1
          : operand_B_bits[20]
              ? 5'h2
              : operand_B_bits[19]
                  ? 5'h3
                  : operand_B_bits[18]
                      ? 5'h4
                      : operand_B_bits[17]
                          ? 5'h5
                          : operand_B_bits[16]
                              ? 5'h6
                              : operand_B_bits[15]
                                  ? 5'h7
                                  : operand_B_bits[14]
                                      ? 5'h8
                                      : operand_B_bits[13]
                                          ? 5'h9
                                          : operand_B_bits[12]
                                              ? 5'hA
                                              : operand_B_bits[11]
                                                  ? 5'hB
                                                  : operand_B_bits[10]
                                                      ? 5'hC
                                                      : operand_B_bits[9]
                                                          ? 5'hD
                                                          : operand_B_bits[8]
                                                              ? 5'hE
                                                              : operand_B_bits[7]
                                                                  ? 5'hF
                                                                  : operand_B_bits[6]
                                                                      ? 5'h10
                                                                      : operand_B_bits[5]
                                                                          ? 5'h11
                                                                          : operand_B_bits[4]
                                                                              ? 5'h12
                                                                              : operand_B_bits[3]
                                                                                  ? 5'h13
                                                                                  : operand_B_bits[2]
                                                                                      ? 5'h14
                                                                                      : operand_B_bits[1]
                                                                                          ? 5'h15
                                                                                          : 5'h16;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:21:33, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:91:52, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:46:21, src/main/scala/chisel3/util/Mux.scala:58:84
  wire [53:0] _recB_rawIn_subnormFract_T =
    {31'h0, operand_B_bits[22:0]} << recB_rawIn_normDist;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:21:33, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:46:21, :52:33, src/main/scala/chisel3/util/Mux.scala:58:84
  wire [8:0]  _recB_rawIn_adjustedExp_T_4 =
    (recB_rawIn_isZeroExpIn
       ? {4'hF, ~recB_rawIn_normDist}
       : {1'h0, operand_B_bits[30:23]}) + {7'h20, recB_rawIn_isZeroExpIn ? 2'h2 : 2'h1};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7, :21:33, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:45:19, :48:30, :54:10, :55:18, :57:9, :58:14, src/main/scala/chisel3/util/Mux.scala:58:84
  wire [2:0]  _recB_T_1 =
    recB_rawIn_isZeroExpIn & ~(|(operand_B_bits[22:0]))
      ? 3'h0
      : _recB_rawIn_adjustedExp_T_4[8:6];	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7, :21:33, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:46:21, :48:30, :49:34, :57:9, :60:30, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/recFNFromFN.scala:48:{15,50}
  wire [32:0] recB =
    {operand_B_bits[31],
     _recB_T_1[2:1],
     _recB_T_1[0] | (&(_recB_rawIn_adjustedExp_T_4[8:7])) & (|(operand_B_bits[22:0])),
     _recB_rawIn_adjustedExp_T_4[5:0],
     recB_rawIn_isZeroExpIn
       ? {_recB_rawIn_subnormFract_T[21:0], 1'h0}
       : operand_B_bits[22:0]};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:21:33, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:44:18, :46:21, :48:30, :49:34, :52:{33,46,64}, :57:9, :61:{32,57}, :64:28, :70:33, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/recFNFromFN.scala:48:{15,76}, :50:{23,41}
  reg  [31:0] add_result;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:53:29
  reg  [31:0] mul_result;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:54:29
  wire        is_writing = io_data_write_n == 2'h2;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7, :28:38
  wire        add_result_rawIn_isInf = (&(_f_add_io_out[31:30])) & ~(_f_add_io_out[29]);	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:40:23, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:41, :57:{33,36}
  wire        add_result_isSubnormal = $signed({1'h0, _f_add_io_out[31:23]}) < 10'sh82;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:40:23, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/fNFromRecFN.scala:51:38, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:48:30, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :60:27
  wire        mul_result_rawIn_isInf = (&(_f_mul_io_out[31:30])) & ~(_f_mul_io_out[29]);	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:47:23, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:41, :57:{33,36}
  wire        mul_result_isSubnormal = $signed({1'h0, _f_mul_io_out[31:23]}) < 10'sh82;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:47:23, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/fNFromRecFN.scala:51:38, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:48:30, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :60:27
  wire [23:0] _add_result_denormFract_T_1 =
    {1'h0, |(_f_add_io_out[31:29]), _f_add_io_out[22:1]} >> 5'h1 - _f_add_io_out[27:23];	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:40:23, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/fNFromRecFN.scala:52:{35,47}, :53:{38,42}, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:48:30, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :52:{28,53}
  wire [23:0] _mul_result_denormFract_T_1 =
    {1'h0, |(_f_mul_io_out[31:29]), _f_mul_io_out[22:1]} >> 5'h1 - _f_mul_io_out[27:23];	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:47:23, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/fNFromRecFN.scala:52:{35,47}, :53:{38,42}, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:48:30, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :52:{28,53}
  always @(posedge clock) begin	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
    if (reset) begin	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
      operand_A_bits <= 32'h0;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:20:33
      operand_B_bits <= 32'h0;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:21:33
    end
    else begin	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
      if (is_writing & ~(|io_address))	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:20:33, :28:38, :29:22, :30:{25,37}, :31:28
        operand_A_bits <= io_data_in;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:20:33
      if (is_writing & (|io_address) & io_address == 6'h4)	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:21:33, :28:38, :29:22, :30:{25,37}, :32:{32,44}
        operand_B_bits <= io_data_in;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:21:33
    end
    add_result <=
      {_f_add_io_out[32],
       (add_result_isSubnormal ? 8'h0 : _f_add_io_out[30:23] + 8'h7F)
         | {8{(&(_f_add_io_out[31:30])) & _f_add_io_out[29] | add_result_rawIn_isInf}},
       add_result_isSubnormal
         ? _add_result_denormFract_T_1[22:0]
         : add_result_rawIn_isInf ? 23'h0 : _f_add_io_out[22:0]};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:40:23, :53:29, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/fNFromRecFN.scala:51:38, :53:{42,60}, :56:16, :58:{27,45}, :60:{15,21,44}, :62:16, :64:20, :66:12, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:{33,41}, :57:33, :59:25, :61:49
    mul_result <=
      {_f_mul_io_out[32],
       (mul_result_isSubnormal ? 8'h0 : _f_mul_io_out[30:23] + 8'h7F)
         | {8{(&(_f_mul_io_out[31:30])) & _f_mul_io_out[29] | mul_result_rawIn_isInf}},
       mul_result_isSubnormal
         ? _mul_result_denormFract_T_1[22:0]
         : mul_result_rawIn_isInf ? 23'h0 : _f_mul_io_out[22:0]};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:47:23, :54:29, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/fNFromRecFN.scala:51:38, :53:{42,60}, :56:16, :58:{27,45}, :60:{15,21,44}, :62:16, :64:20, :66:12, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:{33,41}, :57:33, :59:25, :61:49
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
      `FIRRTL_BEFORE_INITIAL	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
    initial begin	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
      `ifdef INIT_RANDOM_PROLOG_	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
        `INIT_RANDOM_PROLOG_	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
        end	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
        operand_A_bits = _RANDOM[2'h0];	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7, :20:33
        operand_B_bits = _RANDOM[2'h1];	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7, :21:33
        add_result = _RANDOM[2'h2];	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7, :53:29
        mul_result = _RANDOM[2'h3];	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7, :54:29
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
      `FIRRTL_AFTER_INITIAL	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  AddRecFN f_add (	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:40:23
    .io_a   (recA),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/recFNFromFN.scala:50:41
    .io_b   (recB),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/recFNFromFN.scala:50:41
    .io_out (_f_add_io_out)
  );	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:40:23
  MulRecFN f_mul (	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:47:23
    .io_a   (recA),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/recFNFromFN.scala:50:41
    .io_b   (recB),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/recFNFromFN.scala:50:41
    .io_out (_f_mul_io_out)
  );	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:47:23
  assign io_data_out =
    io_address == 6'hC
      ? mul_result
      : io_address == 6'h8
          ? add_result
          : io_address == 6'h4 ? operand_B_bits : (|io_address) ? 32'h0 : operand_A_bits;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7, :20:33, :21:33, :30:25, :32:32, :53:29, :54:29, :56:46
  assign io_data_ready = 1'h1;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7, src/main/scala/chisel3/util/Mux.scala:58:84
  assign io_uo_out = 8'h0;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7
  assign io_user_interrupt = 1'h0;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/Borg.scala:6:7, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromFN.scala:48:30
endmodule

