// Generated by CIRCT firtool-1.137.0-1-gfcc42190a
module MulFullRawFN(	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:47:7
  input         io_a_isNaN,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
                io_a_isInf,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
                io_a_isZero,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
                io_a_sign,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
  input  [9:0]  io_a_sExp,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
  input  [24:0] io_a_sig,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
  input         io_b_isNaN,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
                io_b_isInf,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
                io_b_isZero,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
                io_b_sign,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
  input  [9:0]  io_b_sExp,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
  input  [24:0] io_b_sig,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
  output        io_invalidExc,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
                io_rawOut_isNaN,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
                io_rawOut_isInf,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
                io_rawOut_isZero,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
                io_rawOut_sign,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
  output [9:0]  io_rawOut_sExp,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
  output [47:0] io_rawOut_sig	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:49:16
);

  assign io_invalidExc =
    io_a_isNaN & ~(io_a_sig[22]) | io_b_isNaN & ~(io_b_sig[22]) | io_a_isInf & io_b_isZero
    | io_a_isZero & io_b_isInf;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:47:7, :58:{44,60,76}, :66:{45,71}, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/common.scala:82:{46,49,56}
  assign io_rawOut_isNaN = io_a_isNaN | io_b_isNaN;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:47:7, :70:35
  assign io_rawOut_isInf = io_a_isInf | io_b_isInf;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:47:7, :59:38
  assign io_rawOut_isZero = io_a_isZero | io_b_isZero;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:47:7, :60:40
  assign io_rawOut_sign = io_a_sign ^ io_b_sign;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:47:7, :61:36
  assign io_rawOut_sExp = io_a_sExp + io_b_sExp - 10'h100;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:47:7, :62:{36,48}
  assign io_rawOut_sig = {23'h0, io_a_sig} * {23'h0, io_b_sig};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:47:7, :63:35
endmodule

