// Generated by CIRCT firtool-1.137.0-1-gfcc42190a
module MulRawFN(	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:75:7
  input         io_a_isNaN,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
                io_a_isInf,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
                io_a_isZero,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
                io_a_sign,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
  input  [9:0]  io_a_sExp,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
  input  [24:0] io_a_sig,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
  input         io_b_isNaN,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
                io_b_isInf,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
                io_b_isZero,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
                io_b_sign,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
  input  [9:0]  io_b_sExp,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
  input  [24:0] io_b_sig,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
  output        io_invalidExc,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
                io_rawOut_isNaN,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
                io_rawOut_isInf,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
                io_rawOut_isZero,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
                io_rawOut_sign,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
  output [9:0]  io_rawOut_sExp,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
  output [26:0] io_rawOut_sig	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:77:16
);

  wire [47:0] _mulFullRaw_io_rawOut_sig;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:84:28
  MulFullRawFN mulFullRaw (	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:84:28
    .io_a_isNaN       (io_a_isNaN),
    .io_a_isInf       (io_a_isInf),
    .io_a_isZero      (io_a_isZero),
    .io_a_sign        (io_a_sign),
    .io_a_sExp        (io_a_sExp),
    .io_a_sig         (io_a_sig),
    .io_b_isNaN       (io_b_isNaN),
    .io_b_isInf       (io_b_isInf),
    .io_b_isZero      (io_b_isZero),
    .io_b_sign        (io_b_sign),
    .io_b_sExp        (io_b_sExp),
    .io_b_sig         (io_b_sig),
    .io_invalidExc    (io_invalidExc),
    .io_rawOut_isNaN  (io_rawOut_isNaN),
    .io_rawOut_isInf  (io_rawOut_isInf),
    .io_rawOut_isZero (io_rawOut_isZero),
    .io_rawOut_sign   (io_rawOut_sign),
    .io_rawOut_sExp   (io_rawOut_sExp),
    .io_rawOut_sig    (_mulFullRaw_io_rawOut_sig)
  );	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:84:28
  assign io_rawOut_sig =
    {_mulFullRaw_io_rawOut_sig[47:22], |(_mulFullRaw_io_rawOut_sig[21:0])};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:75:7, :84:28, :93:{10,15,37,55}
endmodule

