// Generated by CIRCT firtool-1.137.0-1-gfcc42190a
module MulRecFN(	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:100:7
  input  [32:0] io_a,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:102:16
                io_b,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:102:16
  output [32:0] io_out	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:102:16
);

  wire        _mulRawFN_io_invalidExc;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
  wire        _mulRawFN_io_rawOut_isNaN;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
  wire        _mulRawFN_io_rawOut_isInf;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
  wire        _mulRawFN_io_rawOut_isZero;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
  wire        _mulRawFN_io_rawOut_sign;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
  wire [9:0]  _mulRawFN_io_rawOut_sExp;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
  wire [26:0] _mulRawFN_io_rawOut_sig;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
  MulRawFN mulRawFN (	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
    .io_a_isNaN       ((&(io_a[31:30])) & io_a[29]),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:{33,41}
    .io_a_isInf       ((&(io_a[31:30])) & ~(io_a[29])),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:41, :57:{33,36}
    .io_a_isZero      (~(|(io_a[31:29]))),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :52:{28,53}
    .io_a_sign        (io_a[32]),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:59:25
    .io_a_sExp        ({1'h0, io_a[31:23]}),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :52:53, :60:27
    .io_a_sig         ({1'h0, |(io_a[31:29]), io_a[22:0]}),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :52:{28,53}, :61:{44,49}
    .io_b_isNaN       ((&(io_b[31:30])) & io_b[29]),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:{33,41}
    .io_b_isInf       ((&(io_b[31:30])) & ~(io_b[29])),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:41, :57:{33,36}
    .io_b_isZero      (~(|(io_b[31:29]))),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :52:{28,53}
    .io_b_sign        (io_b[32]),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:59:25
    .io_b_sExp        ({1'h0, io_b[31:23]}),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :52:53, :60:27
    .io_b_sig         ({1'h0, |(io_b[31:29]), io_b[22:0]}),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/rawFloatFromRecFN.scala:51:21, :52:{28,53}, :61:{44,49}
    .io_invalidExc    (_mulRawFN_io_invalidExc),
    .io_rawOut_isNaN  (_mulRawFN_io_rawOut_isNaN),
    .io_rawOut_isInf  (_mulRawFN_io_rawOut_isInf),
    .io_rawOut_isZero (_mulRawFN_io_rawOut_isZero),
    .io_rawOut_sign   (_mulRawFN_io_rawOut_sign),
    .io_rawOut_sExp   (_mulRawFN_io_rawOut_sExp),
    .io_rawOut_sig    (_mulRawFN_io_rawOut_sig)
  );	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
  RoundRawFNToRecFN_e8_s24 roundRawFNToRecFN (	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:121:15
    .io_invalidExc (_mulRawFN_io_invalidExc),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
    .io_in_isNaN   (_mulRawFN_io_rawOut_isNaN),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
    .io_in_isInf   (_mulRawFN_io_rawOut_isInf),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
    .io_in_isZero  (_mulRawFN_io_rawOut_isZero),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
    .io_in_sign    (_mulRawFN_io_rawOut_sign),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
    .io_in_sExp    (_mulRawFN_io_rawOut_sExp),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
    .io_in_sig     (_mulRawFN_io_rawOut_sig),	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:113:26
    .io_out        (io_out)
  );	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/MulRecFN.scala:121:15
endmodule

