// Generated by CIRCT firtool-1.137.0-1-gfcc42190a
module RoundRawFNToRecFN_e8_s24(	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:295:5
  input         io_invalidExc,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:299:16
                io_in_isNaN,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:299:16
                io_in_isInf,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:299:16
                io_in_isZero,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:299:16
                io_in_sign,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:299:16
  input  [9:0]  io_in_sExp,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:299:16
  input  [26:0] io_in_sig,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:299:16
  output [32:0] io_out	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:299:16
);

  RoundAnyRawFNToRecFN_ie8_is26_oe8_os24 roundAnyRawFNToRecFN (	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:310:15
    .io_invalidExc (io_invalidExc),
    .io_in_isNaN   (io_in_isNaN),
    .io_in_isInf   (io_in_isInf),
    .io_in_isZero  (io_in_isZero),
    .io_in_sign    (io_in_sign),
    .io_in_sExp    (io_in_sExp),
    .io_in_sig     (io_in_sig),
    .io_out        (io_out)
  );	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:310:15
endmodule

