// Generated by CIRCT firtool-1.137.0-1-gfcc42190a
module RoundAnyRawFNToRecFN_ie8_is26_oe8_os24(	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:48:5
  input         io_invalidExc,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:58:16
                io_in_isNaN,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:58:16
                io_in_isInf,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:58:16
                io_in_isZero,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:58:16
                io_in_sign,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:58:16
  input  [9:0]  io_in_sExp,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:58:16
  input  [26:0] io_in_sig,	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:58:16
  output [32:0] io_out	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:58:16
);

  wire [8:0]  _roundMask_T_1 = ~(io_in_sExp[8:0]);	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:156:37, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:52:21
  wire [64:0] _GEN = {59'h0, _roundMask_T_1[5:0]};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:52:21, :59:26, :76:56
  wire [64:0] roundMask_shift = $unsigned($signed(65'sh10000000000000000 >>> _GEN));	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:76:56
  wire [15:0] _roundMask_T_12 =
    {8'h0, roundMask_shift[57:50]} | {roundMask_shift[49:42], 8'h0};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:76:56, :77:20, :78:22
  wire [15:0] _roundMask_T_22 =
    {4'h0, _roundMask_T_12[15:4] & 12'hF0F} | {_roundMask_T_12[11:0] & 12'hF0F, 4'h0};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:77:20
  wire [15:0] _roundMask_T_32 =
    {2'h0, _roundMask_T_22[15:2] & 14'h3333} | {_roundMask_T_22[13:0] & 14'h3333, 2'h0};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:77:20
  wire [64:0] roundMask_shift_1 = $unsigned($signed(65'sh10000000000000000 >>> _GEN));	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:76:56
  wire [24:0] _roundMask_T_73 =
    _roundMask_T_1[8]
      ? (_roundMask_T_1[7]
           ? {~(_roundMask_T_1[6]
                  ? 22'h0
                  : ~{{1'h0, _roundMask_T_32[15:1] & 15'h5555}
                        | {_roundMask_T_32[14:0] & 15'h5555, 1'h0},
                      roundMask_shift[58],
                      roundMask_shift[59],
                      roundMask_shift[60],
                      roundMask_shift[61],
                      roundMask_shift[62],
                      roundMask_shift[63]}),
              3'h7}
           : {22'h0,
              _roundMask_T_1[6]
                ? {roundMask_shift_1[0], roundMask_shift_1[1], roundMask_shift_1[2]}
                : 3'h0})
      : 25'h0;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:52:21, :58:25, :59:26, :62:24, :67:24, :68:58, :73:{17,21,32}, :76:56, :77:20, :78:22
  wire        _common_underflow_T_4 = _roundMask_T_73[0] | io_in_sig[26];	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:120:57, :159:23, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:62:24
  wire [25:0] _GEN_0 = {_roundMask_T_73[24:1], _common_underflow_T_4, 1'h1};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:159:{23,42}, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:62:24
  wire [25:0] _roundPosBit_T =
    io_in_sig[26:1] & {1'h1, ~(_roundMask_T_73[24:1]), ~_common_underflow_T_4} & _GEN_0;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:58:16, :159:{23,42}, :162:53, :163:{28,46}, :164:40, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:62:24
  wire [25:0] roundedSig =
    (|_roundPosBit_T)
      ? {1'h0, io_in_sig[26:2] | {_roundMask_T_73[24:1], _common_underflow_T_4}} + 26'h1
        & ~((|_roundPosBit_T) & (io_in_sig[25:0] & _GEN_0) == 26'h0
              ? {_roundMask_T_73[24:1], _common_underflow_T_4, 1'h1}
              : 26'h0)
      : {1'h0, io_in_sig[26:2] & {~(_roundMask_T_73[24:1]), ~_common_underflow_T_4}};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:58:16, :159:{23,42}, :163:{28,46}, :164:{40,56}, :165:{42,62}, :173:16, :174:{32,49,57}, :175:{21,25,64}, :177:35, :180:{30,43,47}, home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/primitives.scala:62:24
  wire [10:0] sRoundedExp = {io_in_sExp[9], io_in_sExp} + {9'h0, roundedSig[25:24]};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:173:16, :185:{40,54}
  wire        common_totalUnderflow = $signed(sRoundedExp) < 11'sh6B;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:185:40, :200:31
  wire        isNaNOut = io_invalidExc | io_in_isNaN;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:235:34
  wire        notNaN_isInfOut =
    io_in_isInf | ~isNaNOut & ~io_in_isInf & ~io_in_isZero
    & $signed(sRoundedExp[10:7]) > 4'sh2;	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:185:40, :196:{30,50}, :235:34, :237:{22,33,36,61,64}, :238:32, :248:32
  assign io_out =
    {~isNaNOut & io_in_sign,
     sRoundedExp[8:0] & ~(io_in_isZero | common_totalUnderflow ? 9'h1C0 : 9'h0)
       & {2'h3, ~notNaN_isInfOut, 6'h3F} | (notNaN_isInfOut ? 9'h180 : 9'h0)
       | (isNaNOut ? 9'h1C0 : 9'h0),
     isNaNOut | io_in_isZero | common_totalUnderflow
       ? {isNaNOut, 22'h0}
       : io_in_sig[26] ? roundedSig[23:1] : roundedSig[22:0]};	// home/gonsolo/work/borg_tinyqv/borg_peripheral/borg/src/RoundAnyRawFNToRecFN.scala:48:5, :120:57, :173:16, :185:40, :187:37, :189:16, :190:27, :191:27, :200:31, :235:34, :248:32, :250:22, :252:24, :253:{14,18,32}, :264:17, :265:{14,18}, :276:15, :277:{16,73}, :278:16, :280:{12,22,38}, :281:16, :286:33
endmodule

